FROM node:16.13.0-alpine3.14 as build-stage
WORKDIR /app

COPY ./frontend/package.json ./
RUN npm install
COPY ./frontend .
RUN npm run build


FROM python:3.10-slim as run-stage
ENV PYTHONUNBUFFERED True
WORKDIR /app

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . ./
COPY --from=build-stage /app/build ./frontend/build

CMD ["python", "main.py"]